// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: WeaknessScan.proto

package hello_grpc_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeaknessScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slice   string `protobuf:"bytes,1,opt,name=slice,proto3" json:"slice,omitempty"`
	Time    string `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Block   string `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	Detail  string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WeaknessScanRequest) Reset() {
	*x = WeaknessScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WeaknessScan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeaknessScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeaknessScanRequest) ProtoMessage() {}

func (x *WeaknessScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_WeaknessScan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeaknessScanRequest.ProtoReflect.Descriptor instead.
func (*WeaknessScanRequest) Descriptor() ([]byte, []int) {
	return file_WeaknessScan_proto_rawDescGZIP(), []int{0}
}

func (x *WeaknessScanRequest) GetSlice() string {
	if x != nil {
		return x.Slice
	}
	return ""
}

func (x *WeaknessScanRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *WeaknessScanRequest) GetBlock() string {
	if x != nil {
		return x.Block
	}
	return ""
}

func (x *WeaknessScanRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *WeaknessScanRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WeaknessScanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack  string `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	Next string `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
}

func (x *WeaknessScanResponse) Reset() {
	*x = WeaknessScanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WeaknessScan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeaknessScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeaknessScanResponse) ProtoMessage() {}

func (x *WeaknessScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_WeaknessScan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeaknessScanResponse.ProtoReflect.Descriptor instead.
func (*WeaknessScanResponse) Descriptor() ([]byte, []int) {
	return file_WeaknessScan_proto_rawDescGZIP(), []int{1}
}

func (x *WeaknessScanResponse) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

func (x *WeaknessScanResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

var File_WeaknessScan_proto protoreflect.FileDescriptor

var file_WeaknessScan_proto_rawDesc = []byte{
	0x0a, 0x12, 0x57, 0x65, 0x61, 0x6b, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x63, 0x61, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x62, 0x0a,
	0x13, 0x57, 0x65, 0x61, 0x6b, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0d, 0x0a, 0x05, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x12, 0x0c, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x12, 0x0d, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x12, 0x0e, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x12, 0x0f, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x22, 0x31, 0x0a, 0x14, 0x57, 0x65, 0x61, 0x6b, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x63, 0x61,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0b, 0x0a, 0x03, 0x61, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x12, 0x0c, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x32, 0x5b, 0x0a, 0x08, 0x57, 0x65, 0x61, 0x6b, 0x6e, 0x65, 0x73, 0x73,
	0x12, 0x4f, 0x0a, 0x0e, 0x57, 0x65, 0x61, 0x6b, 0x6e, 0x65, 0x73, 0x73, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x57, 0x65, 0x61,
	0x6b, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x57, 0x65, 0x61, 0x6b, 0x6e,
	0x65, 0x73, 0x73, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x3b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_WeaknessScan_proto_rawDescOnce sync.Once
	file_WeaknessScan_proto_rawDescData = file_WeaknessScan_proto_rawDesc
)

func file_WeaknessScan_proto_rawDescGZIP() []byte {
	file_WeaknessScan_proto_rawDescOnce.Do(func() {
		file_WeaknessScan_proto_rawDescData = protoimpl.X.CompressGZIP(file_WeaknessScan_proto_rawDescData)
	})
	return file_WeaknessScan_proto_rawDescData
}

var file_WeaknessScan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_WeaknessScan_proto_goTypes = []interface{}{
	(*WeaknessScanRequest)(nil),  // 0: service.WeaknessScanRequest
	(*WeaknessScanResponse)(nil), // 1: service.WeaknessScanResponse
}
var file_WeaknessScan_proto_depIdxs = []int32{
	0, // 0: service.Weakness.WeaknessUpload:input_type -> service.WeaknessScanRequest
	1, // 1: service.Weakness.WeaknessUpload:output_type -> service.WeaknessScanResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_WeaknessScan_proto_init() }
func file_WeaknessScan_proto_init() {
	if File_WeaknessScan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_WeaknessScan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeaknessScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WeaknessScan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeaknessScanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_WeaknessScan_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_WeaknessScan_proto_goTypes,
		DependencyIndexes: file_WeaknessScan_proto_depIdxs,
		MessageInfos:      file_WeaknessScan_proto_msgTypes,
	}.Build()
	File_WeaknessScan_proto = out.File
	file_WeaknessScan_proto_rawDesc = nil
	file_WeaknessScan_proto_goTypes = nil
	file_WeaknessScan_proto_depIdxs = nil
}
